[TASK] Enhance Altera build scripts
* User selects from existing board designs, if --board parameter
  is not provided as input argument
* Default board setting replaced by selection functionality

Change-Id: I353ee282f01ad26ce8b19774632738110ef6861c

diff --git a/drivers/altera-nios2/drv_daemon/build/create-this-drv b/drivers/altera-nios2/drv_daemon/build/create-this-drv
--- a/drivers/altera-nios2/drv_daemon/build/create-this-drv
+++ b/drivers/altera-nios2/drv_daemon/build/create-this-drv
@@ -65,8 +65,13 @@ if [ -z "${OPLK_BASE_DIR}" ]; then
     OPLK_BASE_DIR=$(readlink -f "${SCRIPTDIR}/../../../..")
 fi
 
+# include functions
+. ${OPLK_BASE_DIR}/tools/altera-nios2/shell_functions
+
 if [ -z "${BOARD_PATH}" ]; then
-    BOARD_PATH=${OPLK_BASE_DIR}/hardware/boards/terasic-de2-115/mn-dual-hostif-gpio
+    # user selects from existing boards
+    BOARD_PATH=`select_dir_abs ${OPLK_BASE_DIR}/hardware/boards 'board.settings' 'grep -e dual -e drv'`
+    test $? -ne 0 && echo "$0 failed!" && exit
 fi
 
 chmod +x ${OPLK_BASE_DIR}/tools/altera-nios2/drivers.sh
