Fixed EplLinRelease and improved X86 Qt demo
- EplApiLinuxKernel.c: fixed hang in EplLinRelease after failing initialization
- X86 Qt demo: improved EplLoad script and Makefile; added error message box
  for initialization errors

diff --git a/Examples/X86/Linux/gnu/demo_mn_8139_qt/EplLoad b/Examples/X86/Linux/gnu/demo_mn_8139_qt/EplLoad
--- a/Examples/X86/Linux/gnu/demo_mn_8139_qt/EplLoad
+++ b/Examples/X86/Linux/gnu/demo_mn_8139_qt/EplLoad
@@ -1,9 +1,19 @@
 #!/bin/sh
 
-echo "check if high resolution timer support is available..."
+
+if [ $USER != "root" ] ; then
+
+  echo "Please run 'sudo $0'"
+
+  exit
+fi
+
+
+echo -n "Check if high resolution timer support is available..."
 
 cat /proc/timer_list | grep 'hres_active.*1' > /dev/null
 if [ "$?" -ne "0" ] ; then
+  echo "  Failed"
   echo
   echo "  High resolution timer support is NOT active."
   echo "  Maybe you need to add 'acpi=force' to kernel command line"
@@ -13,16 +23,33 @@ if [ "$?" -ne "0" ] ; then
   echo
   
   exit
+else
+  echo "  OK"
 fi
 
 
-echo "load EPL module: initializing..."
+echo -n "Searching for RTL8139 nic..."
 
 module="epl"
 
 # unbind network card from ethernet driver
 pciid=$(lspci | grep RTL-8139 | awk "{printf \"0000:\"\$1}")
-echo "unbinding pci device $pciid"
+if [ -z $pciid ] ; then
+  echo "  Failed"
+  echo
+  echo "  No network interface controller with"
+  echo "  Realtek RTL8139 chip found!"
+  echo
+  echo "The EPL module cannot be loaded!"
+  echo
+  
+  exit
+else
+  echo "  OK"
+fi
+
+
+echo "unbinding PCI device $pciid"
 echo -n $pciid > /sys/bus/pci/drivers/8139too/unbind
 
 
@@ -31,10 +58,22 @@ if [ -d /etc/udev/rules.d ] ; then
     cp 50-openPOWERLINK.rules /etc/udev/rules.d
 fi
 
+echo "Loading EPL module..."
+
 # invoke insmod with all arguments we got
 # and use a pathname, as insmod doesn't look in . by default
-/sbin/insmod ./$module.ko $* || exit 1
+/sbin/insmod ./$module.ko $*
 
+if [ "$?" -ne "0" ] ; then
+  echo " Loading of EPL module failed"
+  exit 1
+else
+  echo "EPL module successfully loaded."
+  echo
+  echo "Please start the POWERLINK demo application."
+  echo
+
+fi
 
 exit 0
 
