[FIX] Add return ability to create-this-fpga scripts
Change-Id: I74878fdb8aada2446ebfa170c689bda33e7ecf8f

diff --git a/fpga/boards/altera/TERASIC_DE2-115/mn_par_host/create-this-fpga b/fpga/boards/altera/TERASIC_DE2-115/mn_par_host/create-this-fpga
--- a/fpga/boards/altera/TERASIC_DE2-115/mn_par_host/create-this-fpga
+++ b/fpga/boards/altera/TERASIC_DE2-115/mn_par_host/create-this-fpga
@@ -1,11 +1,39 @@
 #!/bin/sh
 # This script does the following steps:
-#  1. Generate the Qsys design "top_mn"
+#  1. Generate the Qsys design
 #  2. Compile the Quartus II design
-ip-generate --outputdirectory=top_mn/synthesis/ \
+
+# Quartus Project name
+QUARTUS_PRJ=POWERLINK_MN
+
+# Qsys toplevel name
+QSYS_PRJ=top_mn
+
+ip-generate --outputdirectory=${QSYS_PRJ}/synthesis/ \
             --file-set=QUARTUS_SYNTH \
-            --reportfile=sopcinfo:top_mn.sopcinfo \
-            --reportfile=html:top_mn.html \
-            --reportfile=qip:top_mn/synthesis/top_mn.qip \
-            --component-file=top_mn.qsys
-quartus_cmd POWERLINK_MN.qpf -c POWERLINK_MN.qsf
+            --reportfile=sopcinfo:${QSYS_PRJ}.sopcinfo \
+            --reportfile=html:${QSYS_PRJ}.html \
+            --reportfile=qip:${QSYS_PRJ}/synthesis/${QSYS_PRJ}.qip \
+            --component-file=${QSYS_PRJ}.qsys
+
+#check return
+if [ $? -ne 0 ]; then
+    exit 1
+fi
+
+#Workaround: Remove done file
+if [ -f ${QUARTUS_PRJ}.done ]
+then
+    rm ${QUARTUS_PRJ}.done
+fi
+
+quartus_cmd ${QUARTUS_PRJ}.qpf -c ${QUARTUS_PRJ}.qsf
+
+#Workaround: Quartus returned unsuccessful if done file doesn't exist
+if [ ! -f ${QUARTUS_PRJ}.done ]
+then
+    echo "Failed!"
+    exit 1
+fi
+
+exit 0
