[FEATURE] Add additional devices to Edrv82573
- Adding additional derivates of the Intel Gigabit PCI Express chips
  into the driver
- Change EplLoad/EplUnload script to detect different chips handled
  by a single driver. If more than one device is found, the user
  could select which one to use.

Change-Id: I3dbb5aa3024bf902a0ee5573c9a63bdb21152e58

diff --git a/Examples/X86/Linux/gnu/tools/EplLoad b/Examples/X86/Linux/gnu/tools/EplLoad
--- a/Examples/X86/Linux/gnu/tools/EplLoad
+++ b/Examples/X86/Linux/gnu/tools/EplLoad
@@ -1,9 +1,56 @@
-#!/bin/sh
-
+#!/bin/bash
 ###############################################################################
 #
-# Script to load openPOWERLINK module
-# 
+#  (c) SYSTEC electronic GmbH, D-07973 Greiz, August-Bebel-Str. 29
+#      www.systec-electronic.com
+#
+# (c) Bernecker + Rainer Industrie-Elektronik Ges.m.b.H.
+#     B&R Strasse 1, A-5142 Eggelsberg, www.br-automation.com
+#
+#  Project:      openPOWERLINK
+#
+#  Description:  Script to load openPOWERLINK kernel module
+#
+#  License:
+#
+#    Redistribution and use in source and binary forms, with or without
+#    modification, are permitted provided that the following conditions
+#    are met:
+#
+#    1. Redistributions of source code must retain the above copyright
+#       notice, this list of conditions and the following disclaimer.
+#
+#    2. Redistributions in binary form must reproduce the above copyright
+#       notice, this list of conditions and the following disclaimer in the
+#       documentation and/or other materials provided with the distribution.
+#
+#    3. Neither the name of SYSTEC electronic GmbH nor the names of its
+#       contributors may be used to endorse or promote products derived
+#       from this software without prior written permission. For written
+#       permission, please contact info@systec-electronic.com.
+#
+#    THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
+#    "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
+#    LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
+#    FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
+#    COPYRIGHT HOLDERS OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
+#    INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
+#    BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
+#    LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
+#    CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
+#    LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
+#    ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
+#    POSSIBILITY OF SUCH DAMAGE.
+#
+#    Severability Clause:
+#
+#        If a provision of this License is or becomes illegal, invalid or
+#        unenforceable in any jurisdiction, that shall not affect:
+#        1. the validity or enforceability in that jurisdiction of any other
+#           provision of this License; or
+#        2. the validity or enforceability in other jurisdictions of that or
+#           any other provision of this License.
+#
 ###############################################################################
 
 ###############################################################################
@@ -11,26 +58,26 @@
 #
 usage()
 {
-        echo >&2 \
-        "usage: EplLoad [-h] [-c <cdcfile>] [-t <tracer>] [-s] <powerlink_module> [module args]\n" \
-        "-c, specify CDC file\n" \
-        "-s, set priority (used by udev rule)\n" \
-        "-t, set ftrace tracer\n" \
-        "-h, print usage\n"
-        exit 1
+    echo >&2 \
+    "usage: EplLoad [-h] [-c <cdcfile>] [-t <tracer>] [-s] <powerlink_module> [module args]\n" \
+    "-c, specify CDC file\n" \
+    "-s, set priority (used by udev rule)\n" \
+    "-t, set ftrace tracer\n" \
+    "-h, print usage\n"
+    exit 1
 }
 
 loadfail()
 {
-	echo "  Failed"
-        echo
-        echo "  No network interface controller with"
-        echo "  $nic chip found!"
-        echo
-        echo "The EPL module cannot be loaded!"
-        echo
+    echo "  Failed"
+    echo
+    echo "  No network interface controller with"
+    echo "  $nic chip found!"
+    echo
+    echo "The EPL module cannot be loaded!"
+    echo
 
-        exit 1
+    exit 1
 }
 
 ###############################################################################
@@ -62,15 +109,15 @@ done
 # Used by udev rule to set priority
 if [ "$setprio" = "true" ] ; then
     # Set real-time priority -81 for Ethernet ISR thread
-    chrt -f -p 80 `ps -C \`ps -e -o comm |grep ^irq/.*epl\$\` -o pid --no-headers` 
+    chrt -f -p 80 `ps -C \`ps -e -o comm |grep ^irq/.*epl\$\` -o pid --no-headers`
     exit
 fi
 
 ###############################################################################
 # must be root to load module
 if [ $USER != "root" ] ; then
-  echo "Please run 'sudo $0'"
-  exit
+    echo "Please run 'sudo $0'"
+    exit
 fi
 
 ###############################################################################
@@ -81,18 +128,17 @@ echo -n "Check if high resolution timer support is available..."
 
 cat /proc/timer_list | grep 'hres_active.*1' > /dev/null
 if [ "$?" -ne "0" ] ; then
-  echo "  Failed"
-  echo
-  echo "  High resolution timer support is NOT active."
-  echo "  Maybe you need to add 'acpi=force' to kernel command line"
-  echo "  or try it on a more recent X86 processor."
-  echo
-  echo "The POWERLINK module is and will not be loaded!"
-  echo
-  
-  exit
+    echo "  Failed"
+    echo
+    echo "  High resolution timer support is NOT active."
+    echo "  Maybe you need to add 'acpi=force' to kernel command line"
+    echo "  or try it on a more recent X86 processor."
+    echo
+    echo "The POWERLINK module is and will not be loaded!"
+    echo
+    exit
 else
-  echo "  OK"
+    echo "  OK"
 fi
 
 ###############################################################################
@@ -100,46 +146,64 @@ fi
 # Check if module does exist
 #
 if [ ! -f  `dirname $0`/$module ] ; then
-    echo "POWERLINK module `dirname $0`/$module.ko does not exist!"
+    echo "  openPOWERLINK module `dirname $0`/$module.ko does not exist!"
+    echo "  Please specify an existing module!"
     exit 1
 fi
 
+module=`basename $module .ko`
+
 ###############################################################################
 #
-# Check if it is a demo with application
+# Check if it is a kernel module witch includes the demo application
 #
 echo "$module" | grep -q "demo"
 isndemo=$?
 
 ###############################################################################
-
 #
 # Check if suitable ethernet card is available
+# If we find more than one ethernet card we provide a prompt to select one.
 #
-module=`basename $module .ko`
-if echo "$module" | grep -q "8139" ; then
-    nic="RTL-8139"
-    nicdev="8139too"
-elif echo "$module" | grep -q "82573" ; then
-    nic="Intel Corporation 82573"
-    nicdev="e1000e"
-else
-    echo "No valid network interface controller specified!"
-    usage
-fi
+let i=0
+while read line; do
+    device=`echo $line | cut -f1 -d","`
+    devname=`echo $line | cut -f2 -d","`
+    driver=`echo $line | cut -f3 -d","`
 
-echo -n "Searching for ${nic} nic..."
+    if echo "$module" | grep -q "$device" ; then
+        lspci=`lspci | grep "${devname}"`
+        pciid=$(lspci | grep "${devname}" | awk "{printf \"0000:\"\$1}")
+        if [ ! -z "$lspci" ]; then
+            let i=i+1
+            echo "$i) $lspci"
+            if [ -z $devs ] ; then
+                devs="$pciid"
+                drivers="$driver"
+            else
+                devs="$devs,$pciid"
+                drivers="$drivers,$driver"
+            fi
+        fi
+    fi
+done < devices.txt
 
-# unbind network card from ethernet driver
-pciid=$(lspci | grep "${nic}" | awk "{printf \"0000:\"\$1}")
-if [ -z $pciid ] ; then
+if [ $i -gt 1 ] ; then
+    read -p "Please select the ethernet controller to use > " num
+elif [ $i -eq 1 ]; then
+    num=1
+elif [ $i -eq 0 ] ; then
     loadfail
-else
-    echo "  OK"
 fi
+
+pciid=`echo $devs | cut -f$num -d","`
+driver=`echo $drivers | cut -f$num -d","`
+
+#echo $driver $pciid
+#exit 1
 
 echo "unbinding PCI device $pciid"
-echo -n $pciid > /sys/bus/pci/drivers/${nicdev}/unbind
+echo -n $pciid > /sys/bus/pci/drivers/${driver}/unbind
 
 ###############################################################################
 #
@@ -148,12 +212,7 @@ if [ "$isndemo" -ne "0" ] ; then
     if [ -d /etc/udev/rules.d ] ; then
         EPLLOAD_PATH=`dirname $(readlink -f ${0})`
         cat 50-openPOWERLINK.rules | sed "s#EPLLOAD_PATH#${EPLLOAD_PATH}#" > /etc/udev/rules.d/50-openPOWERLINK.rules
-        which service > /dev/null
-        if [ "$?" -eq "0" ] ; then
-            service udev reload
-        else
-            /etc/init.d/udev reload
-        fi
+        udevadm control --reload-rules
     fi
 fi
 
@@ -177,24 +236,30 @@ if [ "$?" -ne "0" ] ; then
     exit 1
 else
     if [ "$isndemo" -ne "0" ] ; then
-    echo "POWERLINK module successfully loaded."
-    echo
-    echo "Please start the POWERLINK demo application."
-    echo
+        echo "POWERLINK module successfully loaded."
+        echo
+        echo "Please start the POWERLINK demo application."
+        echo
     else
         echo "POWERLINK demo application successfully loaded."
-        echo    
+        echo
     fi
 fi
 
-# Set real-time priority -82 for hr-timer threads
-chrt -f -p 81 `ps -C sirq-hrtimer/0 -o pid --no-headers`
-chrt -f -p 81 `ps -C sirq-hrtimer/1 -o pid --no-headers` 
+# Set real-time priority -82 for hrtimer thread
+# We only have to set hrtimer thread for core 0 because the stack
+# binds to the first core!
+numproc=`ps aux | grep -c "sirq-hrtimer/0"`
+if [ $numproc -gt 1 ] ; then
+    echo Adjusting priority of hrtimer thread
+    chrt -f -p 81 `ps -C sirq-hrtimer/0 -o pid --no-headers`
+fi
+
 # For kernel-queue shared-buffer thread, priority -80 is set in ShbIpc-LinuxKernel.c
 
 # For Ethernet ISR thread, priority -81 is set (for kernel stack module by udev rule!)
 if [ "$isndemo" -eq "0" ] ; then
-    chrt -f -p 80 `ps -C \`ps -e -o comm |grep ^irq/.*epl*\$\` -o pid --no-headers` 
+    chrt -f -p 80 `ps -C \`ps -e -o comm |grep ^irq/.*epl*\$\` -o pid --no-headers`
 fi
 
 # Enable tracing
