Several cleanups and fixes
- Cleanup set_prio and move it into tools
- Some bugfixes and cleanups in EplLoad
- Several fixes in CMakeList.txt files
- Correct CDC file in demo_kernel and demo_qt
- Replace wrong xap.h file

diff --git a/Examples/X86/Linux/gnu/tools/set_prio b/Examples/X86/Linux/gnu/tools/set_prio
--- a/Examples/X86/Linux/gnu/tools/set_prio
+++ b/Examples/X86/Linux/gnu/tools/set_prio
@@ -3,9 +3,24 @@
 # Shell script to set priority of some important kernel threads
 #
 
+interface=
+
+usage()
+{
+        echo >&2 \
+        "usage: set_prio <network_interface>\n"
+        exit 1
+}
+
 if [ $USER != "root" ] ; then
   echo "Please run 'sudo $0'"
   exit
+fi
+
+if [ "$#" -ne "1" ] ; then
+    usage
+else
+    interface=$1
 fi
 
 echo -n "Check if high resolution timer support is available..."
@@ -26,12 +41,28 @@ else
   echo "  OK"
 fi
 
+echo -n "Check if interface $interface exists..."
+ps -e -o comm | grep -q ^irq/.*${interface}\$
+if [ "$?" -ne "0" ] ; then
+    echo "  Failed"
+    echo "  Interrupt thread for interface $interface not found! Priority couldn't be set!"
+    echo
+
+    exit
+else
+    echo "  OK"
+fi
+
+echo "Setting thread priorities..."
+echo
+
 # Set real-time priority openPOWERLINK dependant threads
 chrt -f -p 80 `ps -C sirq-hrtimer/0 -o pid --no-headers`
 chrt -f -p 80 `ps -C sirq-hrtimer/1 -o pid --no-headers`
-chrt -f -p 70 `ps -C \`ps -e -o comm |grep ^irq/.*eth1\$\` -o pid --no-headers` 
+chrt -f -p 70 `ps -C \`ps -e -o comm |grep ^irq/.*${interface}\$\` -o pid --no-headers` 
 chrt -f -p 60 `ps -C sirq-net-rx/0 -o pid --no-headers` 
 chrt -f -p 60 `ps -C sirq-net-rx/1 -o pid --no-headers`
+
 exit 0
 
 
